import { useRouter } from 'next/router'
import Head from "next/head";
 
import Header from "@/src/components/Header/header";
import Footer from "@/src/components/Footer";
import BannerPage from "@/src/components/Banner/bannerPage";
import ServiceInfo from '@/src/components/commonComponents/serviceInfo';
import Featured from '@/src/components/commonComponents/featured';
import CustomizedService from '@/src/components/commonComponents/customizedSerives';
import { servicesPageData } from '@/src/shared/constant';


export default function DbgServices() {
    const router = useRouter();
    const currentUrl = typeof window !== 'undefined' ? window.location.href : '';
    const { service } = router.query;

    const servicePageResponse = servicesPageData.Page.filter((item,index)=>{
        return service == item.Title
    })

 

    const  pageText = {
        title: `Our  ${service?.toLocaleUpperCase()} Service `,
        breadcrumb: [
            {
                link: "/",
                text: "Home"
            },
            {
                link: `/dbg-services/${service}`,
                text: service
            }
        ]
    }
    return (
    <>
      <Head>
        <title>Digital Business Growers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      <main>
      <div className="mainHeader-banner">
      <Header/>
      <BannerPage pageText={pageText} />
      </div>
      <div className='servicedatilsPage'>
      <ServiceInfo 
      serviceTitle = {servicePageResponse[0]?.h3Headeing}  
      serviceSummary = {servicePageResponse[0]?.summary} 
      serviceImg = {servicePageResponse[0]?.img}
      />
      <Featured Featured = {servicePageResponse[0]?.Featured} />
      <CustomizedService 
       CustomizeService = {servicePageResponse[0]?.customized}
       keyPoints4 = {servicePageResponse[0]?.keyPoints4} 
       />
      </div>

      </main>
      <Footer />
    </>
    );
}