import Head from "next/head";

 
import Header from "@/src/components/Header/header";

import Footer from "@/src/components/Footer";
import BannerPage from "@/src/components/Banner/bannerPage";
import CompanyInfo from "@/src/components/commonComponents/companyInfo";
import AboutMission from "@/src/components/commonComponents/aboutMission";
import Advisor from "@/src/components/commonComponents/advisor";


export default function Contact() {
   const  pageText = {
        title: "Conatct Us  to Grow Your Business Digitally",
        breadcrumb: [
            {
                link: "/",
                text: "Home"
            },
            {
                link: "#",
                text: "Contact Us"
            }
        ]
    }
  return (
    <>
      <Head>
        <title>Digital Business Growers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      <main>
      <div className="mainHeader-banner">
      <Header/>
      <BannerPage pageText={pageText} />
      </div>
      <section className="contact-page-sec">
        <div className="container">
            <div className="bg">
            <div className="row">
                <div className="col-lg-6 content-left">
                    <h2>Get In Touch</h2>
        
                    <div className="cont-detail">
                        <p> 
                            If you have any questions or need more information about our services, please feel free to contact us. We are always happy to help you.
                        </p>
                        <ul>
                            <li><div className="icon"><i className="fa fa-map-marker" aria-hidden="true">
                              <img src="/assests/images/footer-icon/location.svg" alt="location" width={15}/>
                              </i></div>55 Main Street, 2nd block Malborne, Australia 324565</li>
                            <li><div className="icon"><i className="fa fa-phone" aria-hidden="true">
                              <img src="/assests/images/footer-icon/call.svg" alt="phone" width={15}/>
                              </i></div> <a href="tel:+919650232509">+91 965 (0232) 509</a></li>
                            <li><div className="icon"><i className="fa fa-envelope" aria-hidden="true">
                              <img src="/assests/images/footer-icon/message.svg" alt="mail" width={15}/>
                              </i></div> <a href="mailto:digitalbusinesss@gmail.com">digitalbusinesss@gmail.com</a></li>
                        </ul>
                        <div className="map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3596.698175292917!2d-80.41303612390759!3d25.648141013287045!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88d9c19df8b9ff4b%3A0xe3d5d9e26fa4d897!2s13378%20SW%20128th%20St%2C%20Miami%2C%20FL%2033186%2C%20USA!5e0!3m2!1sen!2sin!4v1719580964705!5m2!1sen!2sin" width="100%" height="300"  allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>
                    </div>
                </div>
                <div className="col-lg-6 content-right">
                  <label for="">Your Name</label>
                  <input type="text" placeholder="Your Name" />
                  <label for="">Your Email</label>
                  <input type="email" placeholder="Your Email" />
                  <label for="">Your Subject</label>
                  <input type="text" placeholder="Subject" />
                  <label for="">Your Message</label>
                  <textarea name="" id="" placeholder="Your Message"></textarea>
                  <input type="submit" value="Submit" />
                </div>
            </div>
            </div>
        </div>    
  </section>
    
      <CompanyInfo />


<AboutMission/>


<Advisor />


<Footer/>
       
      </main>
    </>
  );
}
