import Head from "next/head";
import Header from "@/src/components/Header/header";
import DbgTeamComp from "@/src/components/Team";
import BannerPage from "@/src/components/Banner/bannerPage";
import Footer from "@/src/components/Footer";
import Advisor from "@/src/components/commonComponents/advisor";

export default function DbgTeam() {
    const  pageText = {
        title: "Our Team Members are the Best.",
        breadcrumb: [
            {
                link: "/",
                text: "Home"
            },
            {
                link: "/dbg-team",
                text: "DBG Team"
            }
        ]
    }

    return (
        <>
      <Head>
        <title>Digital Business Growers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      <main>
      <div className="mainHeader-banner">
      <Header/>
      <BannerPage pageText={pageText} />
      </div>
           <DbgTeamComp />
           </main>
           <Advisor/>
           <Footer/>
        </>
    )
}