import Head from "next/head";
import Image from "next/image";
 
import Banner from "@/src/components/Banner/banner";
import Header from "@/src/components/Header/header";
import IncreaseSell from "@/src/components/IncreaseSell";
import ServiceBox from "@/src/components/ServiceBox";
import DrivenQuwality from  "@/src/components/DrivenQuwality"
import MakeBusiness from "@/src/components/MakeBusiness";

import DeliverdProject from "@/src/components/DeliverdProject";
import Footer from "@/src/components/Footer";
import dynamic from "next/dynamic";
const WorkProcess = dynamic(() => import("@/src/components/WorkProcess"));



export default function Home() {
  return (
    <>
      <Head>
        <title>Digital Business Growers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      <main>
      <div className="mainHeader-banner">
      <Header/>
      <Banner/>
      </div>
      <IncreaseSell/>
      <ServiceBox />
      <DrivenQuwality/>
      <MakeBusiness/> 
      <WorkProcess/>
      <DeliverdProject/>
    
      <Footer/>

       
      </main>
    </>
  );
}
